# Generated by Django 5.1.2 on 2024-10-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='ast_representation',
            field=models.TextField(default='none'),
        ),
    ]
